#  ███████╗███████╗███████╗██╗  ██╗     ██████╗ ██████╗ ███╗   ██╗███████╗██╗ ██████╗
#  ██╔════╝██╔════╝██╔════╝██║  ██║    ██╔════╝██╔═══██╗████╗  ██║██╔════╝██║██╔════╝
#  ███████╗█████╗  ███████╗███████║    ██║     ██║   ██║██╔██╗ ██║█████╗  ██║██║  ███╗
#  ╚════██║██╔══╝  ╚════██║██╔══██║    ██║     ██║   ██║██║╚██╗██║██╔══╝  ██║██║   ██║
#  ███████║███████╗███████║██║  ██║    ╚██████╗╚██████╔╝██║ ╚████║██║     ██║╚██████╔╝
#  ╚══════╝╚══════╝╚══════╝╚═╝  ╚═╝     ╚═════╝ ╚═════╝ ╚═╝  ╚═══╝╚═╝     ╚═╝ ╚═════╝
#
#  Smart session manager for the terminal
#  https://github.com/joshmedeski/sesh

blacklist = ["scratch"]

# common

[[session]]
name = "Downloads"
path = "~/Downloads"
startup_command = "yazi"

[[session]]
name = "Projects"
path = "~/Projects"
startup_command = "configure_task -type op"

[[session]]
name = "home (~)"
path = "~"

# configs

[[session]]
name = "dotfiles"
path = "~/.config/"

[[session]]
name = "wezterm config"
path = "~/.config/wezterm"
startup_command = "nvim wezterm.lua"

[[session]]
name = "neovim config"
path = "~/.config/nvim"

[[session]]
name = "sesh config"
path = "~/.config/sesh"
startup_command = "nvim sesh.toml"
preview_command = "bat --language=toml --style=snip --color=always ~/.config/sesh/sesh.toml"

[[session]]
name = "tmux config"
path = "~/.config/tmux"
startup_command = "nvim tmux.conf"
preview_command = "bat --language=bash --style=snip --color=always ~/.config/tmux/tmux.conf"

# plugins
[[session]]
name = "lazy plugins"
path = "~/.local/share/nvim/lazy"
startup_command = "sesh connect (ls | fzf --ansi --no-border --preview 'glow -s light {}/README.md' --preview-window=right:70,border-none) && exit"
# TODO: add `--hide-tmux` to fzf command (or switch to sesh preview)
# startup_command = "sesh connect (ls | fzf --ansi --no-border --preview 'glow -s light {}/README.md' --preview-window=right:70,border-none --hide-tmux) && exit"

[[session]]
name = "tmux plugins"
path = "~/.config/tmux/plugins"
startup_command = "sesh connect (ls | fzf --ansi --no-border --preview 'glow -s light {}/README.md' --preview-window=right:70,border-none) && exit"
