[mgr]
ratio = [1, 2, 4]
sort_by = "alphabetical"
sort_sensitive = false
sort_reverse = false
sort_dir_first = true
sort_translit = false
linemode = "size"
show_hidden = true
show_symlink = true
title_format = "Yazi: {cwd}"

[preview]
tab_size = 2
max_width = 2000
max_height = 1200
cache_dir = ""
image_filter = "triangle"
image_quality = 75
sixel_fraction = 15
ueberzug_scale = 1
ueberzug_offset = [0, 0, 0, 0]

[opener]
edit = [
  { run = '$EDITOR "$@"', block = true, for = "unix" },
  { run = 'code "%*"', orphan = true, for = "windows" },
]
open = [
  { run = 'xdg-open "$@"', desc = "Open", for = "linux" },
  { run = 'open "$@"', desc = "Open", for = "macos" },
  { run = 'start "%1"', orphan = true, desc = "Open", for = "windows" },
]
browse = [
  {run = 'firefox-nightly --new-tab "$@"', desc = "Browse Webpage", orphan = true}
]
reveal = [
  { run = 'open -R "$1"', desc = "Reveal", for = "macos" },
  { run = 'explorer /select,%1', orphan = true, desc = "Reveal", for = "windows" },
  { run = '''exiv2 "$1"; echo "Press enter to exit"; read''', block = true, desc = "Show EXIF", for = "unix" },
]
extract = [
  { run = 'unar "$1"', desc = "Extract here", for = "unix" },
  { run = 'unar "%1"', desc = "Extract here", for = "windows" },
]
play = [
  { run = 'mpv "$@"', orphan = true, for = "unix" },
  { run = 'mpv "%1"', orphan = true, for = "windows" },
  { run = '''mediainfo "$1"; echo "Press enter to exit"; read''', block = true, desc = "Show media info", for = "unix" },
]
view = [
    { run = 'haruna "$@"', desc = "View video" }
]

[open]
rules = [
  { name = "*/", use = [
    "edit",
    "open",
    "reveal",
  ] },

  { mime = "text/*", use = [
    "edit",
    "browse",
    "reveal",
  ] },
  { mime = "image/*", use = [
    "open",
    "reveal",
  ] },
  { mime = "video/*", use = [
    "view",
    "reveal",
  ] },
  { mime = "audio/*", use = [
    "play",
    "reveal",
  ] },
  { mime = "inode/empty", use = [
    "edit",
    "reveal",
  ] },

  { mime = "application/json", use = [
    "edit",
    "reveal",
  ] },
  { mime = "*/javascript", use = [
    "edit",
    "reveal",
  ] },

  { mime = "application/zip", use = [
    "extract",
    "reveal",
  ] },
  { mime = "application/gzip", use = [
    "extract",
    "reveal",
  ] },
  { mime = "application/r", use = [
    "extract",
    "reveal",
  ] },
  { mime = "application/bzip", use = [
    "extract",
    "reveal",
  ] },
  { mime = "application/bzip2", use = [
    "extract",
    "reveal",
  ] },
  { mime = "application/7z-compressed", use = [
    "extract",
    "reveal",
  ] },
  { mime = "application/rar", use = [
    "extract",
    "reveal",
  ] },

  { mime = "*", use = [
    "open",
    "reveal",
  ] },
]

[tasks]
micro_workers = 5
macro_workers = 10
bizarre_retry = 5

[plugins]
preload = []
prepend_previewers = [{ mime = "image/heic", run = "heic" }]

[log]
enabled = false
